### ISSUE TITLE
kill a "zombie" server

### ISSUE THREAD

**Issue by jborbely** [MSLNZ/msl-loadlib#14]
The 32-bit server can continue to run even after the program running the client's script has terminated.

Consider fetching some metadata (e.g., process id) from the server when the client connects.

**Comment by eugenkleinschmidt** [comment]
Is this solved? It seems that this is still happening. At least I cannot remove venv after I closed my app
![image](https://github.com/MSLNZ/msl-loadlib/assets/10838796/d66878ae-590e-4430-82d3-09fdce6c62a5)

**Comment by jborbely** [comment]
If you are using a version of `msl-loadlib` >= 0.6.0 then you are using a version that has the _kill code_ implemented; however, there are many reasons why the _kill code_ will not work 100% of the time (especially on Windows).

If this is a one-off issue and you just want to delete your venv directory, either 1) reboot your computer 2) open `Task Manager` and manually end the tasks for the 32-bit server processes (there are 2 running processes with the description "Access a 32-bit library from 64-bit Python").

If you want help debugging why your 32-bit server is not shutting down gracefully, then I would need a lot more information from you -- so please create a new issue and provide example code.
