### ISSUE TITLE
ImportError: bad magic number in 'app': b'U\r\r\n'

### ISSUE THREAD

**Issue by fleimgruber** [MSLNZ/msl-loadlib#25]
Background: I was using msl-loadlib 0.7.0 two years ago with Python 3.6 and in a frozen environment using https://github.com/marcelotduarte/cx_Freeze. Now with msl-loadlib 0.7.0 with a newer Python version 3.8 I stumbled across https://github.com/MSLNZ/msl-loadlib/issues/21. I subsequently updated msl-loadlib (tested with 0.8.0. and 0.9.0) and now the following code (in spirit of https://msl-loadlib.readthedocs.io/en/latest/interprocess_communication.html):

```
Client64.__init__(
    self, module32="app.can_wrapper", append_sys_path=vendor_path,
)
```

errors with

```
msl.loadlib.exceptions.ConnectionTimeoutError: Timeout after 10.0 seconds. Could not connect to 127.0.0.1:63307
ImportError: bad magic number in 'app': b'U\r\r\n'
The missing module must be in sys.path (see the --append-sys-path option)
```

The magic number in the exception is the one from the 3.8 env installation:

```
>>> import importlib.util
>>> importlib.util.MAGIC_NUMBER
b'U\r\r\n'
```

The code in question works well when executed within a regular Python script (unfrozen env) with all mentioned msl-loadlib versions.

Are there any best practices for using msl-loadlib in frozen environments? Do you have any idea whether it is the import machinery of msl-loadlib or the input machinery of cx_Freeze that is causing this?

*edit*: I was vaguely recalling something similar and indeed found an old issue I reported with cx_Freeze, please see https://github.com/marcelotduarte/cx_Freeze/issues/525

**Comment by jborbely** [comment]
Prior to reading your message I have never tried to use msl-loadlib in a frozen environment, so unfortunately I can recommend any best practices. I just tried doing this and I cannot reproduce your error. Here's what I did:

1. Here are the relevant version numbers
```console
> python -VV
Python 3.8.11 (default, Aug  6 2021, 09:57:55) [MSC v.1916 64 bit (AMD64)]
> python -c "from msl.loadlib import __version__; print(__version__)"
0.9.0
> cxfreeze --version
cxfreeze 6.7 Copyright (c) 2020-2021 Marcelo Duarte. All rights reserved. Copyright (c) 2007-2020 Anthony Tuininga.
All rights reserved. Copyright (c) 2001-2006 Computronix Corporation. All rights reserved.
```

2. Created a script called _issue25.py_
```python
import os
from msl.loadlib import Client64, Server32

class Server(Server32):

    def __init__(self, host, port):
        super(Server, self).__init__(
            os.path.join(Server32.examples_dir(), 'cpp_lib32'), 'cdll', host, port
        )

    def add(self, a, b):
        return self.lib.add(a, b)

class Client(Client64):

    def __init__(self):
        super(Client, self).__init__(__file__)

    def add(self, a, b):
        return self.request32('add', a, b)

if __name__ == '__main__':
    c = Client()
    print('3 + 5 =', c.add(3, 5))
```
3. Executed the script
```console
> python issue25.py
3 + 5 = 8
```
4. Froze the script 
```console
> cxfreeze -c issue25.py
```
5. Ran the frozen script
```console
> build\exe.win-amd64-3.8\issue25.exe
3 + 5 = 8
```
Would you be able to share a minimal example that raises this error?

**Comment by fleimgruber** [comment]
Thanks a lot for looking into this and your efforts!

Since the code base I am working on does it a bit differently, I tried to strip it down of any specifics and provided a MRE here: https://github.com/fleimgruber/msl-loadlib-issue25

Some things to consider:
1. Uses a conda environment as the Python installation.
2. In the actual code base there are more DLLs under `vendor\` which are orchestrated by `lib_wrapper.CAN32Wrapper` (via `clr` from pythonnet), the `__init__` and `Connect` should give a rough idea (these code paths are not hit in this MRE, just to illustrate the reason why Server32 is in another module here).
3. Freezing is done using `cx_Freeze.setup` and the `setup_freeze.py` module, see also below.

Steps to reproduce:

    > conda create -n msl-loadlib-issue25 python=3.8.5
    > conda activate msl-loadlib-issue25

    > python -VV
    Python 3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)]

    > pip install msl-loadlib

    > python -c "from msl.loadlib import __version__; print(__version__)"
    0.9.0

    > pip install pythonnet

    > python -c "from clr import __version__; print(__version__)"
    2.5.1

    > pip install cx_Freeze

    > cxfreeze --version
    cxfreeze 6.7 Copyright (c) 2020-2021 Marcelo Duarte. All rights reserved. Copyright (c) 2007-2020 Anthony Tuininga. All rights
    reserved. Copyright (c) 2001-2006 Computronix Corporation. All rights reserved.

    > python .\setup_freeze.py build

    > cd build\exe.win-amd64-3.8
    > .\issue25.exe
    Traceback (most recent call last):
      File "C:\Users\LeimgruberF\AppData\Local\Continuum\Miniconda3\envs\msl-loadlib-issue25\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 104, in run
        module_init.run(name + "__main__")
      File "C:\Users\LeimgruberF\AppData\Local\Continuum\Miniconda3\envs\msl-loadlib-issue25\lib\site-packages\cx_Freeze\initscripts\Console.py", line 15, in run
        exec(code, module_main.__dict__)
      File "app/issue25.py", line 31, in <module>
      File "app/issue25.py", line 19, in __init__
      File "C:\Users\LeimgruberF\AppData\Local\Continuum\Miniconda3\envs\msl-loadlib-issue25\lib\site-packages\msl\loadlib\client64.py", line 199, in __init__
        utils.wait_for_server(host, port, timeout)
      File "C:\Users\LeimgruberF\AppData\Local\Continuum\Miniconda3\envs\msl-loadlib-issue25\lib\site-packages\msl\loadlib\utils.py", line 282, in wait_for_server
        raise ConnectionTimeoutError(
    msl.loadlib.exceptions.ConnectionTimeoutError: Timeout after 10.0 seconds. Could not connect to 127.0.0.1:61160
    ImportError: bad magic number in 'app': b'U\r\r\n'
    The missing module must be in sys.path (see the --append-sys-path option)
    The paths in sys.path are:
      C:\Users\LEIMGR~1\AppData\Local\Temp\_MEI208242
      C:\Users\LeimgruberF\dev\msl-loadlib-issue25\build\exe.win-amd64-3.8
      C:\Users\LeimgruberF\dev\msl-loadlib-issue25\build\exe.win-amd64-3.8
      C:\Users\LeimgruberF\dev\msl-loadlib-issue25\build\exe.win-amd64-3.8\lib\library.zip
      C:\Users\LeimgruberF\dev\msl-loadlib-issue25\build\exe.win-amd64-3.8\lib
      C:\Users\LeimgruberF\dev\msl-loadlib-issue25\build\exe.win-amd64-3.8\vendor
    Cannot start the 32-bit server.

**Comment by fleimgruber** [comment]
Following the lead in https://github.com/marcelotduarte/cx_Freeze/issues/525#issuecomment-902759437, when replacing `build\exe.win-amd64-3.8\lib\app\__init__.pyc` and `build\exe.win-amd64-3.8\lib\app\lib_wrapper.pyc` with their `*.py` source versions, then I get this error:

```
❯ .\issue25.exe
Traceback (most recent call last):
  File "C:\Users\LeimgruberF\AppData\Local\Continuum\Miniconda3\envs\msl-loadlib-issue25\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 104, in run
    module_init.run(name + "__main__")
  File "C:\Users\LeimgruberF\AppData\Local\Continuum\Miniconda3\envs\msl-loadlib-issue25\lib\site-packages\cx_Freeze\initscripts\Console.py", line 15, in run
    exec(code, module_main.__dict__)
  File "app/issue25.py", line 31, in <module>
  File "app/issue25.py", line 19, in __init__
  File "C:\Users\LeimgruberF\AppData\Local\Continuum\Miniconda3\envs\msl-loadlib-issue25\lib\site-packages\msl\loadlib\client64.py", line 199, in __init__
    utils.wait_for_server(host, port, timeout)
  File "C:\Users\LeimgruberF\AppData\Local\Continuum\Miniconda3\envs\msl-loadlib-issue25\lib\site-packages\msl\loadlib\utils.py", line 282, in wait_for_server
    raise ConnectionTimeoutError(
msl.loadlib.exceptions.ConnectionTimeoutError: Timeout after 10.0 seconds. Could not connect to 127.0.0.1:50254
Instantiating the 32-bit server raised the following exception:
  FileNotFoundException: Unable to find assembly 'cpp_lib32'.
   at Python.Runtime.CLRModule.AddReference(String name)
Cannot start the 32-bit server.
```

which is to be expected and should work with the actual 3rd party DLLs in place. Now this workaround is not really feasible as the final version shipped to customers uses Cython for compilation to avoid the shallow pyc.

**Comment by jborbely** [comment]
Thanks for the MRE. I could reproduce the bad-magic-number error.

Re-freezing the 32-bit server using a 32-bit version of Python that is the same Python version that cxfreeze used for the build does fix this issue. I don't see any other solution.

To make the frozen 32-bit server yourself you would install the appropriate Windows x86 version from [python.org](https://www.python.org/downloads/) and then follow the instructions [here](https://msl-loadlib.readthedocs.io/en/stable/refreeze.html). I recommend downloading from python.org and not from a 32-bit (mini)conda installer because I can confirm that the python.org installer will solve this issue.

Please let me know if you have any problems creating your own 32-bit server.

**Comment by fleimgruber** [comment]
Thanks for trying it out and your suggested fix. I managed to re-freeze the server using poetry + pyenv (finally an excuse to look into both...) following your instructions ("Using the CLI"). Can confirm it fixes this issue.

Thanks again for your support and your efforts on msl-loadlib!
