### ISSUE TITLE
Connection is refused occasionally

### ISSUE THREAD

**Issue by deisi** [MSLNZ/msl-loadlib#28]
I use msl-load lib within a project of mine. However occasionally it fails connecting client and server with:

``` python
self.*conn.request('POST', 'protocol={}&path={}'.format(self.pickleprotocol, self.*pickle_path))
File "http\client.py", line 1239, in request
File "http\client.py", line 1285, in sendrequest
File "http\client.py", line 1234, in endheaders
File "http\client.py", line 1026, in sendoutput
File "http\client.py", line 964, in send
File "http\client.py", line 936, in connect
File "socket.py", line 724, in create_connection
File "socket.py", line 713, in create_connectionConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it
```

I use the latest  release version of ms-lib (0.9.0) with python 3.6 here. The exact same code runs fine like 9 out of 10 times, but occasionally it fails establishing the client serer connection. I was guessing that this is a port issue, but that doesn't seem to be the case, as picking a specific free port leads to the same results. The host is a windows 10 64bit Machine. Any clue what is happening there?

**Comment by jborbely** [comment]
I have not come across this issue before. 

Can you show a minimal example of the code that you are using that raises the error?

If you repeatedly run the following in a Command Prompt does it raise the error?
```console
python -c "from msl.examples.loadlib import Cpp64; c = Cpp64(); print(c.add(4, 5))"
```

**Comment by deisi** [comment]
Minimal example, I dumped it down manually a little, I hope I didn't mess up, but the implementation is minimal anyways. There is only one function in the dll that needs to be called. I haven't tested you simple minimal example yet, but I will try if I can trigger the issue with that as well. 

dll_server.py

``` python

from msl.loadlib import Server32
import ctypes

class DllServer(Server32):

def **init**(self, host, port, quiet, **kwargs):
    super().**init**(kwargs['dll'], kwargs['libtype'], host, port, quiet)

def GenerateKeyExOpt(self, seed):
    p_key = (ctypes.c*ubyte \* 64)()
    ret = self.lib.call_a_function(
    (ctypes.c*ubyte  *len(seed))(*seed), len(seed), p_key
    )
       key = [p_key[i] for i in range(64)]
    return ret, key
```

dll_client.py

``` python
import os
from msl.loadlib import Client64

class DllClient(Client64):
  
    def __init__(self, dll, libtype='windll', **kwargs):
        super().__init__(
            module32='dll_server', append_sys_path=os.path.dirname(__file__),
            dll=dll, libtype=libtype, timeout=10, **kwargs
        )
        self._dllpath = dll

    @property
    def _name(self):
        return os.path.splitext(os.path.basename(self._dllpath))[0]

    def GenerateKeyExOpt(self, seed):
        return self.request32("GenerateKeyExOpt", seed)
```

main.py

``` python
dll = DllClient(dll=dll_path, libtype='cdll')
# This is the point where it fails
# bla bla stuff 
key = dll.GenerateKeyExOpt([1,2,3])
##bla bla bla
        
```

**Comment by jborbely** [comment]
What happens if you temporarily modify your `main.py` script to be something like

```python
import os
from msl.loadlib import Server32
from dll_client import DllClient

dll_path = os.path.join(Server32.examples_dir(), 'cpp_lib32.dll')

dll = DllClient(dll=dll_path, libtype='cdll')
```

Try loading a different DLL to see if instantiating the ``DllClient`` object is more reliable.

**Comment by deisi** [comment]
I just managed to trigger the issue by running:
`from msl.examples.loadlib import Cpp64; c = Cpp64(); print(c.add(4, 5))` from within a python shell but only once so far and only the very first time. Running `python -c "from msl.examples.loadlib import Cpp64; c = Cpp64(); print(c.add(4, 5))"` from the cmd I could not trigger the issue

**Comment by deisi** [comment]
I start to fear it is related to the virus scanner. Maybe for some reason it prevents the TCP socket from opening. On a second try, for what ever reason it doesn't do so any more. I would love to know though what triggers this and how I cam reliably reproduce this.

**Comment by jborbely** [comment]
Yes, you are correct. The 64-bit client uses [HTTPConnection](https://docs.python.org/3/library/http.client.html#http.client.HTTPConnection) to connect with the 32-bit server running on [HTTPServer](https://docs.python.org/3/library/http.server.html#http.server.HTTPServer).

**Comment by jborbely** [comment]
Closed due to inactivity.
