### ISSUE TITLE
msl-loadlib doesn't exist for Python 3.10 in pypi

### ISSUE THREAD

**Issue by totocaca123** [MSLNZ/msl-loadlib#29]
There is no whl file for python 3.10

**Comment by jborbely** [comment]
What

1) operating system
2) bitness of python, and 
3) version of pip 

are you using?

**Comment by totocaca123** [comment]
I run it again and I'm abble to install it. It was a pip issue. So this issue can be rejected
windows 11 x64 
python 3.10.2
