### ISSUE TITLE
loading alternate server32.exe 

### ISSUE THREAD

**Issue by amarco** [MSLNZ/msl-loadlib#35]
Hi All

I have built a custom server32.exe with a more current version of python ect. When I followed the docs it asked to place the files in the site-packages/msl/loadlib folder.
This makes things a little awkward for distributing my solution. I would like to put the new server32.exe file in the same folder as my server32.py file.
Is there a way to specify the filename and location of the server32.exe to use.

Marco

**Comment by jborbely** [comment]
Not in a previous release, but there will be an option in the next release (or available now in the `main` branch).

A `server32_dir` kwarg has been added to `Client64` in a47aeff. This commit only supports specifying the location (directory) and assumes the default filename. Is having control over the filename important?

**Comment by jborbely** [comment]
I see that by the way you used `server32_dir` in issue #36, you don't require control of the filename. How you specified the directory is the way that I was hoping people would instinctively use this keyword argument.

**Comment by amarco** [comment]
Yes I had no objection to the name. One thing that could be added to the freeze script which creates the file is to specifiy a destination so one does not have to navigate into site-packages ect to get the files. Just a thought.

All good I am in production now and am going to tinker away at making a version that is numpy free 😊

**Comment by amarco** [comment]
Hi J S

I am so far into the woods I can see the trees from the forest 😊
Below is code that works nice for me using numpy and a 32 bit dll as previously discussed.
I thought it would be a simple matter of changing the np references to native c_types but man am I ever turned around.
The externall dll takes in a array and populates so when the call completes the array is filled with values.

 def dciGetDeviceChannels(self, deviceNum):
        """
        dciGetDeviceChannels
        int32 __stdcall dciGetDeviceChannels(int32 DeviceNumber, int32* Channels)
        Use Get the device channel list
        Arguments
            int32 DeviceNumber Number of device in list (from 0 to NumDevices-1)
            int32* Channels Channel list array to be filled
        Return value int32
            Success 0: Error
                    1: No error
        Python return is a dictionary:
            {"Status": 0|1, "DeviceNum": int32, "ChannelList": 32bit numpy array}
        Remarks Call this function to get a device channel list.
        """
        maxChans = self.dciDeviceNumChannels(deviceNum)
        channelList = np.zeros(maxChans, dtype=np.int32)
        function = self.lib.dciGetDeviceChannels
        function.argtypes = [c_int32, np.ctypeslib.ndpointer(dtype=np.int32)]
        function.restype = c_int32
        status = True if function(deviceNum, channelList) == 1 else False
        return {"Status": status, "DeviceNum": deviceNum, "ChannelList":channelList}

Below is my ctype only attempt

 def dciGetDeviceChannels(self, deviceNum):
        """
        dciGetDeviceChannels
        int32 __stdcall dciGetDeviceChannels(int32 DeviceNumber, int32* Channels)
        Use Get the device channel list
        Arguments
            int32 DeviceNumber Number of device in list (from 0 to NumDevices-1)
            int32* Channels Channel list array to be filled
        Return value int32
            Success 0: Error
                    1: No error
        Python return is a dictionary:
            {"Status": 0|1, "DeviceNum": int32, "ChannelList": 32bit numpy array}
        Remarks Call this function to get a device channel list.
        """
        maxChans = self.dciDeviceNumChannels(deviceNum)
        PINT32 = POINTER(c_int32*maxChans)
        channelList = (PINT32)()
        function = self.lib.dciGetDeviceChannels
        function.argtypes = [c_int32, PINT32]
        function.restype = c_int32
        status = True if function(deviceNum, byref(channelList) ) == 1 else False
        return {"Status": status, "DeviceNum": deviceNum, "ChannelList":channelList}

And it produces the following error, which I have been unable to get past. Is there something obvious I am missing 😊
***@***.***

**Comment by jborbely** [comment]
Only _values_ can be returned, not a _pointer to values_ (which is how you defined `channelList`).

Something like the following should fix things

```python
# defining argtypes and restype could be moved from the dciGetDeviceChannels method into the __init__ method,
# since they do not depend on the deviceNum value you pass to dciGetDeviceChannels
function = self.lib.dciGetDeviceChannels
function.argtypes = [c_int32, POINTER(c_int32)]
function.restype = c_int32

maxChans = self.dciDeviceNumChannels(deviceNum)
channelList = (c_int32 * maxChans)()
status = True if function(deviceNum, channelList) == 1 else False
return {"Status": status, "DeviceNum": deviceNum, "ChannelList": [c for c in channelList]}
```
