### ISSUE TITLE
TypeError: cannot pickle 'xxx' object

### ISSUE THREAD

**Issue by arturhercoles63** [MSLNZ/msl-loadlib#39]
Durante a utilização da biblioteca usando o recurso de servidor e server tento acessar uma dll .net em 32btis a mesma consegue ser carrega porem ao chamar um objeto acontece um erro.

![image](https://github.com/MSLNZ/msl-loadlib/assets/40493486/fc154099-4b2a-4dc0-8568-629cd5957443)

Quando utilizo x64 para x64 o erro não consegue apenas ao utilizar a função x86 para x64

 # my_client.py
  
    from msl.loadlib import Client64

    class MyClient(Client64):
        """Call a function in 'my_lib.dll' via the 'MyServer' wrapper."""
    
        def __init__(self):
            # Specify the name of the Python module to execute on the 32-bit server (i.e., 'my_server')
            super(MyClient, self).__init__(module32='my_server')
    
        def INIT_(self):
            return self.request32('library')
        
    c = MyClient()
    
    bm = c.INIT_()
    
    INCA = bm.GetOpenedExperiment()
    
    pass
`
# my_server.py

  from msl.loadlib import Server32
  from msl.loadlib import LoadLibrary
  
  class MyServer(Server32):
     
      def __init__(self, host, port, **kwargs):
          super(MyServer, self).__init__('C:\\ETAS\\INCA7.2\\cebra\\incacom.dll', 'net', host, port)
  
      def library(self):
          return self.lib.de.etas.cebra.toolAPI.Inca.Inca()
´

**Comment by jborbely** [comment]
The error that you are getting is correct. When you create the ``Inca`` object in the 32-bit server, the object can only exist in the 32-bit server code. You cannot return the 32-bit version of ``Inca`` to your 64-bit client.

What you must do is keep the ``Inca`` object in the 32-bit server code and make requests to ``Inca`` from the 64-bit client code. Provided that the methods of ``Inca`` return objects like: str, int, float, bool, list, tuple, dict, ... (basically, anything that can be [pickled](https://docs.python.org/3/library/pickle.html)) your code will be okay.

For example, I'll assume that ``GetOpenedExperiment()`` returns an integer, which indicates whether opening the experiment was successful. You could do something like the following

```python
# my_server.py
from msl.loadlib import Server32

class MyServer(Server32):

    def __init__(self, host, port, **kwargs):
        super().__init__('C:\\ETAS\\INCA7.2\\cebra\\incacom.dll', 'net', host, port)
        self.inca = self.lib.de.etas.cebra.toolAPI.Inca.Inca()

    def get_opened_experiment(self):
        return self.inca.GetOpenedExperiment()
```

```python
# my_client.py
from msl.loadlib import Client64

class MyClient(Client64):

    def __init__(self):
        super().__init__(module32='my_server')

    def get_opened_experiment(self):
        return self.request32('get_opened_experiment')
    
c = MyClient()

if c.get_opened_experiment() != 0:
    raise RuntimeError('Cannot open the experiment')

**Comment by arturhercoles63** [comment]
Thank you for the answer, it was very enlightening.

However, this Dll is used as an API to control another application, and most of the API returns objects such as `GetOpenedExperiment()` that are constantly updated over time and with the constant sending and receiving of data.

![image](https://github.com/MSLNZ/msl-loadlib/assets/40493486/a5509c2c-1522-452f-b341-cc0719ea9bfd)

But your library is excellent, good work!


# my_client.py

  from msl.loadlib import Client64
  
  class MyClient(Client64):
      """Call a function in 'my_lib.dll' via the 'MyServer' wrapper."""
  
      def __init__(self):
          # Specify the name of the Python module to execute on the 32-bit server (i.e., 'my_server')
          super(MyClient, self).__init__(module32='my_server')
  
      def experiment(self):
          return self.request32('library')
      
  INCA = MyClient() # Return Object
  
  EXP = INCA.experiment()  # Return Object

EXP.PauseRecording() # Return String

pass

Great work on the library and thanks for the support!

**Comment by jborbely** [comment]
Just keep the 32-bit API objects in the 32-bit server code and the client-server interplay should be okay.

Here are a few examples on how to deal with an API like this

### Case 1: You only need to create a single Experiment instance
```python
# my_server.py
from msl.loadlib import Server32

class MyServer(Server32):

    def __init__(self, host, port, **kwargs):
        super().__init__('C:\\ETAS\\INCA7.2\\cebra\\incacom.dll', 'net', host, port)
        self.inca = self.lib.de.etas.cebra.toolAPI.Inca.Inca()
        self.experiment = self.inca.GetOpenedExperiment()

    def pause_recording(self):
        # PauseRecording returns a string, which can be re-created in the 64-bit memory space
        return self.experiment.PauseRecording()
```
```python
# my_client.py
from msl.loadlib import Client64

class MyClient(Client64):

    def __init__(self):
        super().__init__(module32='my_server')

    def pause_recording(self):
        return self.request32('pause_recording')
    
experiment = MyClient()
print(experiment.pause_recording())
```

### Case 2: You need to create multiple Experiment instances
```python
# my_server.py
from msl.loadlib import Server32

class MyServer(Server32):

    def __init__(self, host, port, **kwargs):
        super().__init__('C:\\ETAS\\INCA7.2\\cebra\\incacom.dll', 'net', host, port)
        self.inca = self.lib.de.etas.cebra.toolAPI.Inca.Inca()
        self.experiment_key = 0
        self.experiments = {}

    def get_opened_experiment(self):
        self.experiment_key += 1
        self.experiments[self.experiment_key] = self.inca.GetOpenedExperiment()
        return self.experiment_key

    def pause_recording(self, experiment_key):
        # PauseRecording returns a string, which can be re-created in the 64-bit memory space
        return self.experiments[experiment_key].PauseRecording()
```
```python
# my_client.py
from msl.loadlib import Client64

class MyClient(Client64):

    def __init__(self):
        super().__init__(module32='my_server')

    def get_opened_experiment(self):
        return self.request32('get_opened_experiment')

    def pause_recording(self, experiment_key):
        return self.request32('pause_recording', key)
    
inca = MyClient()
experiment_key_1 = inca.get_opened_experiment()
experiment_key_2 = inca.get_opened_experiment()
print(inca.pause_recording(experiment_key_2 ))
```
or, in the client code, you could get a bit fancier
```python
# my_client2.py
from msl.loadlib import Client64

class Experiment:

    def __init__(self, key, request32):
        self.key = key
        self.request32 = request32

    def pause_recording(self):
        return self.request32('pause_recording', self.key)

class MyClient(Client64):

    def __init__(self):
        super().__init__(module32='my_server')

    def get_opened_experiment(self):
        key = self.request32('get_opened_experiment')
        return Experiment(key, self.request32) 
    
inca = MyClient()
experiment1 = inca.get_opened_experiment()
experiment2 = inca.get_opened_experiment()
print(experiment2.pause_recording())
```

**Comment by arturhercoles63** [comment]
Thats great, I can now operate the application and this is a big step forward and it seems to be almost completely resolved.
Would it be possible to modify any object within the server after its creation
For example, instead of calling more than one experiment, just recreate it on the server? If this were possible, my problem would be completely solved as:

Getopenexperimet

Startrecording

Sleep(n)

Stop()

SwitchExperiment(args:str = nameofexperiment) #Server32

GetOpenexperiment #Again Server32

**Comment by arturhercoles63** [comment]
> Isso é ótimo, agora posso operar o aplicativo e este é um grande passo à frente e parece estar quase completamente resolvido. Seria possível modificar qualquer objeto dentro do servidor após sua criação Por exemplo, em vez de chamar mais de um experimento, basta recriá-lo no servidor? Se isso fosse possível, meu problema seria completamente resolvido como:
> 
> Getopenexperimet
> 
> Iniciando a gravação
> 
> Sono(n)
> 
> Parar()
> 
> SwitchExperiment(args:str = nameofexperiment) #Server32
> 
> GetOpenexperiment #Again Server32

**Comment by arturhercoles63** [comment]
Very good, I can now operate the application and this is a big step forward and it seems to be almost completely resolved.
Would it be possible to modify any object within the server after its creation
For example, instead of calling more than one experiment, just recreate it on the server? If this were possible my problem would be completely resolved as follows:

Getopenexperimet

Startrecording

Sleep(n)

Stop()

SwitchExperiment(args:str = nameofexperiment) #Server32

GetOpenexperiment #Again Server32

**Comment by jborbely** [comment]
Yes, it is possible to modify an object on the server after it is created.

```python
# my_server.py
from msl.loadlib import Server32

class MyServer(Server32):

    def __init__(self, host, port, **kwargs):
        super().__init__('C:\\ETAS\\INCA7.2\\cebra\\incacom.dll', 'net', host, port)
        self.inca = self.lib.de.etas.cebra.toolAPI.Inca.Inca()
        self.experiment = None

    def get_opened_experiment(self):
        # Usually, an API has a corresponding close/destroy method when a resource is created.
        # I'm not sure if this is true for an Experiment object, but if an Experiment can
        # be closed, it should be. For example, something like the following should be done
        # before GetOpenedExperiment() is called.
        if self.experiment is not None:
            self.experiment.Close()
        
        # Create a reference to a new Experiment object, but do not return it
        self.experiment = self.inca.GetOpenedExperiment()

    def pause_recording(self):
        # PauseRecording returns a string, which can be re-created in the 64-bit memory space
        return self.experiment.PauseRecording()

    def start_recording(self):
        self.experiment.StartRecording()

    def stop(self):
        self.experiment.Stop()
```

```python
# my_client.py
from msl.loadlib import Client64

class MyClient(Client64):

    def __init__(self):
        super().__init__(module32='my_server')

    def get_opened_experiment(self):
        self.request32('get_opened_experiment')

    def pause_recording(self):
        return self.request32('pause_recording')

    def start_recording(self):
        self.request32('start_recording')

    def stop(self):
        self.request32('stop')
    
inca = MyClient()

inca.get_opened_experiment()
inca.start_recording()
print(inca.pause_recording())
inca.stop()

inca.get_opened_experiment()  # a new Experiment object is created on the server
inca.start_recording()
```

**Comment by arturhercoles63** [comment]
Very good, I managed to make all the necessary changes

Thanks a lot for the help!!! Excellent support
