### ISSUE TITLE
32-bit server not shutting down

### ISSUE THREAD

**Issue by snjung** [MSLNZ/msl-loadlib#43]
I have a Python script using msl-loadlib to access a 32bit-dll for communication with external hardware. Everything works smooth just running this script. 

I wanted to add a little tkinter UI for better usability. When calling the script from the GUI, I run into issues, because after execution of the procedure, the 32-bit server will not shut down. This might be intended, since the main thread / GUI is still running. Is there a way to manually call a deconstructor to trigger closing down the server?

**Comment by jborbely** [comment]
Have you tried calling [shutdown_server32()](https://msl-loadlib.readthedocs.io/en/stable/_api/msl.loadlib.client64.html#msl.loadlib.client64.Client64.shutdown_server32) ?

**Comment by snjung** [comment]
Thank you for the hint, this solved the problem. Should have figured this one out by myself ;-)
