### ISSUE TITLE
Still having the issue "cannot find 'server32_windows.exe'"

### ISSUE THREAD

**Issue by dwang-git** [MSLNZ/msl-loadlib#47]
I used pyinstaller to create an executable. But every time when I run the executable, I would have the error as in the attached pic. 
![error](https://github.com/user-attachments/assets/ba71cbca-7923-4393-89c7-3fb16800f386)

I found there was a closed issue: https://github.com/MSLNZ/msl-loadlib/issues/16

But don't know why I'm still having this problem. Thanks!

**Comment by jborbely** [comment]
Have a look [here](https://msl-loadlib.readthedocs.io/en/latest/faq.html#freezing-the-msl-loadlib-package) to see if those instructions help.

**Comment by jborbely** [comment]
I will assume that the instructions in the docs fixed this issue.
